contact/urls.py
from django.urls import path

from contact import views

app_name = 'contact'

urlpatterns = [
    
    
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),

    #Contact
    path('contact/<int:id>/detail/', views.contact, name='contact'),
    path('contact/create/', views.create, name='create'),
    path('contact/<int:id>/update/', views.update, name='update'),
    path('contact/<int:id>/delete/', views.delete, name='delete'),

    #User
    path('user/create/', views.register, name='register')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

#Media
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contact.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Category(models.Model):
    nome = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self) -> str:
        return f'{self.nome}'

class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/' )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True,
        null=True
        )
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True
        )

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'
    

contact/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from contact.models import Contact

class ContactForm(forms.ModelForm):

    picture = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'accept': 'image/*',
            }
        )
    )

   

    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'phone',
                    'email', 'description','category',
                    'picture',
        )
       

    def clean(self):
        cleaned_data = self.cleaned_data
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if first_name == last_name:  
            self.add_error(
                'first_name',
                ValidationError(
                    'Ops!! Primeiro nome igual ao sobrenome.',
                    code='invalid'
                )

            )
        return super().clean()
    

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(
        required=True,
        min_length=3,
    )
    last_name = forms.CharField(
        required=True,
        min_length=3,
    )
    email = forms.EmailField(
        required=True,
    )


    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username', 'password1', 'password2',
        )
    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email = email).exists():
            self.add_error(
                'email',
                ValidationError('Email já cadastrado', code='invalid')
            
            )
        return email

contact/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(
        request,
        'contact/pages/index.html',
          
    )

contact/views/contact_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from contact.models import Contact
from contact.forms import ContactForm


def create(request):
    form_action = reverse('contact:create')

    if request.method == 'POST':
        form =ContactForm(request.POST, request.FILES)
        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            contact = form.save()
           # return redirect('contact:index')
            return redirect('contact:update', id=contact.pk )


        template = 'contact/pages/create.html'
        return render(request, template, context)
    

    context = {
            'form_action': form_action,
            'form': ContactForm()
        }
    template = 'contact/pages/create.html'
    return render(request, template, context)


def update(request, id):
    contact = get_object_or_404(Contact, id=id, show=True)
    form_action = reverse('contact:update', args=(id,))

    if request.method == 'POST':
        form =ContactForm(request.POST, request.FILES, instance=contact )
        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            contact = form.save()
           # return redirect('contact:index')
            return redirect('contact:update', id=contact.pk )


        template = 'contact/pages/create.html'
        return render(request, template, context)
    

    context = {
            'form_action': form_action,
            'form': ContactForm(instance=contact)
        }
    template = 'contact/pages/create.html'
    return render(request, template, context)


def delete(request, id):
    contact = get_object_or_404(
        Contact, pk=id, show=True
    )
    confirmation = request.POST.get('confirmation', 'no')
    
    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')
    
    return render(
        request,
        'contact/pages/contact.html',
        {
            'contact': contact,
            'confirmation': confirmation
        }
    )

contact/views/contact_views.py
from django.shortcuts import render, get_object_or_404, redirect
from contact.models import Contact
from django.core.paginator import Paginator
from django.db.models import Q

def index(request):
    contacts = Contact.objects \
        .all() \
        .filter(show=True)\
        .order_by('-id')
    
    paginator = Paginator(contacts, 8)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos - '
    }
                                                                 
    return render(
        request,
        'contact/pages/index.html',
         context 
    )

def search(request):

    
    search_value = request.GET.get('q', '').strip()
    if(search_value == ''):
        return redirect('contact:index')

    contacts = Contact.objects\
        .filter(show=True)\
        .filter(
            Q(first_name__icontains=search_value) |
            Q(last_name__icontains=search_value) |
            Q(email__icontains=search_value) |
            Q(phone__icontains=search_value) 
            )\
        .order_by('-id')
    
    paginator = Paginator(contacts, 8)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
   
    context = {
        #'contacts': contacts,
        'page_obj': page_obj,
        'site_title': 'Contatos - '
    }
                                                                 
    return render(
        request,
        'contact/pages/index.html',
         context 
    )

def contact(request, id):
    contact = get_object_or_404(
        Contact.objects.filter(show=True), pk=id
        )
    contact_name = f'{contact.first_name} {contact.last_name} - '
    context = {
        'contact':contact,
        'site_title': contact_name
    }

    return render(
        request,
        'contact/pages/contact.html',
        context
    )

contact/views/user_forms.py
from django.shortcuts import render
from contact.forms import RegisterForm

def register(request):

    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            


    context ={
        'form': form
        }

    template = 'contact/pages/register.html'
    return render(request, template, context)

contact/templates/contact/pages/contact.html
{% extends 'global/base.html' %}


{% block content %}
    
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{ contact.first_name}} {{contact.last_name}}
        </h1>

        <p><b>ID: </b> {{ contact.id }}</p>
        <p><b>E-mail: </b> {{ contact.email }}</p>
        <p><b>Phone: </b> {{ contact.phone }}</p>
        <p><b>Category: </b> {{ contact.category.nome }}</p>
        <p><b>Description: </b> {{ contact.description }}</p>
        <p><b>Create: </b> {{ contact.created_date }}</p>
        
        {% if contact.picture %}
        <p>
            
            <img src="{{contact.picture.url}}" alt="{{contact.first_name}}">
        </p>
        {% endif %}
        

        <div class="contact-links">
            <a class="btn btn-link" href="{% url 'contact:update' contact.id %}"> Atualizar</a>
            
            <form action="{% url 'contact:delete' contact.id %}" method="POST">
                {% csrf_token %}
                

                {% if confirmation == 'no' %}
                <input type="hidden" name="confirmation" value="yes">
                <button class="btn btn-link btn-delete">Confirma exclusão?</button>
                    
                {% else %}
                <button class="btn btn-link btn-delete">Excluir</button>
                {% endif %}
            </form>
        </div>
    </div>
    
    

   
{% endblock %}

contact/templates/contact/pages/create.html
{% extends 'global/base.html' %}


{% block content %}
    
  <div class="form-wrapper">
    <h2>Contato</h2>
   
    <form 
        action="{{ form_action }}" 
        method="post"
        enctype="multipart/form-data"
        >
        {% csrf_token %}

      
        {% for field in form %}
            <div class="form-content">
                <div class="form-group">
                    <label for="{{ field.id_for_label}}">{{field.label}}</label>
                    {{ field }}
                    {{ field.errors }}
                </div>
              
            </div>

            <div class="for-group">
                {% if field.value.url and field.name == 'picture'  %}
                <img src="{{ field.value.url}}" alt="">
            {% endif %}
            </div>
        {% endfor %}

        <div class="form-content">
            <div class="form-group">
                <button class="btn" type="submit">Enviar</button>
            </div>
        </div>
    
    
    </form>
  </div>
   
{% endblock %}

contact/templates/contact/pages/index.html
{% extends 'global/base.html' %}


{% block content %}
    
    {% if page_obj %}

    <div class="responsive-table">
        <table class="contacts-table">
            <caption class="table-caption">
                Contacts
            </caption>
            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">Nome</th>
                    <th class="table-header">Phone</th>
                    <th class="table-header">E-mail</th>
                </tr>
            </thead>

            <tbody>
                {% for contact in page_obj %}
                <tr class="table-row">
                    
                    <td class="table-cel"><a  href="{% url 'contact:contact' contact.id %}">{{contact.id}} </a></td> 
                    <td class="table-cel">{{contact.first_name}} {{contact.last_name}}</td>
                    <td class="table-cel">{{contact.phone}}</td>
                    <td class="table-cel">{{contact.email}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    
    
    {% else %}
        <div class="single-contact">
            <h1 class="single-contact-name">
                <p>Nenhum contato encontrado</p>
            </h1>

                
        </div>
    {% endif %}
    
    

   
{% endblock %}

contact/templates/contact/pages/register.html
{% extends 'global/base.html' %}


{% block content %}
    
  <div class="form-wrapper">
    <h2>Novo usuário</h2>
   
    <form 
        action="{{ form_action }}" 
        method="post"
        
        >
        {% csrf_token %}

      
        {% for field in form %}
            <div class="form-content">
                <div class="form-group">
                    <label for="{{ field.id_for_label}}">{{field.label}}</label>
                    {{ field }}
                    {{ field.errors }}
                </div>
              
            </div>

           
        {% endfor %}

        <div class="form-content">
            <div class="form-group">
                <button class="btn" type="submit">Enviar</button>
            </div>
        </div>
    
    
    </form>
  </div>
   
{% endblock %}